language: python
python:
  - "3.6"
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - py.test --cov-report=xml --cov=src
after_success:
  - bash <(curl -s https://codecov.io/bash)